# Default values for the skeleton project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "default-skeleton-team"
domain: &default_domain default.skeleton.team
app_name: "Default skeleton Team"
sender_address: "no-reply@*default_domain"

common:
  config:
    api_uri: "https://*default_domain"
    app_uri: "https://*default_domain"

aws:
  secret:
    aws_access_key_id: ""
    aws_secret_access_key: ""
    bucket_name: ""

mailer:
  secret:
    mailer_user: ""
    mailer_password: ""
  config:
    mailer_host: ""
    mailer_port: ""
    mailer_tls: ""
    rabbitmq_channel: ""

server:
  branch: "develop"
  config:
    allow_front_redirect_pattern: ""
    jwt_token_ttl: "86400"
    backup_code_hash_length: ""
    oauth_allowed_domains: "*default_domain,4xxi.com"
  secret:
    app_secret: ""
    superadmin_pass: ""
    backup_code_salt: ""
    database_url: ""
    google_id: ""
    google_secret: ""
    invitation_salt: ""
    jwt_passphrase: ""
    mailer_url: ""

backuper:
  enable: true
  branch: "latest"
  config:
    aws_bucket_backup_path: ""
    aws_bucket_name: ""
    aws_default_region: ""
    db_host: ""
    db_port: ""
    encrypt: "true"
    slack_channel: '#backup'
    slack_enabled: "false"
    slack_webhook_url: ""
  secret:
    encrypt_pass: ""

client:
  branch: "master"
  secret:
